function ratio = formant_centralization_ratio(formant_frequencies_i, ...
                                              formant_frequencies_a, ...
                                              formant_frequencies_u)

formant_frequencies_i = formant_frequencies_i(:);
formant_frequencies_a = formant_frequencies_a(:);
formant_frequencies_u = formant_frequencies_u(:);

ratio = ( formant_frequencies_u(2) + formant_frequencies_a(2) + ...
          formant_frequencies_i(1) + formant_frequencies_u(1) ) / ...
        ( formant_frequencies_i(2) + formant_frequencies_a(1) );
